import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "../components/ui/provider";
import { ColorModeButton } from "@/components/ui/color-mode";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Provider>
          {children}
          <ColorModeButton />
        </Provider>
      </body>
    </html>
  );
}
